SET XACT_ABORT ON;
BEGIN TRANSACTION;

IF OBJECT_ID(N'dbo.LICHSUGIAOHANG', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.LICHSUGIAOHANG
    (
        Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_LICHSUGIAOHANG PRIMARY KEY,
        MaDonHang INT NOT NULL,
        MaNhanVien INT NULL,
        TrangThai INT NOT NULL,
        LyDo NVARCHAR(200) NULL,
        GhiChu NVARCHAR(1000) NULL,
        AnhBangChung NVARCHAR(500) NULL,
        ThoiGian DATETIME2 NOT NULL CONSTRAINT DF_LICHSUGIAOHANG_ThoiGian DEFAULT SYSDATETIME(),
        ThoiGianHenLai DATETIME2 NULL,
        CONSTRAINT FK_LICHSUGIAOHANG_DONHANG FOREIGN KEY (MaDonHang) REFERENCES dbo.DONHANG(MaDonHang),
        CONSTRAINT FK_LICHSUGIAOHANG_NHANVIEN FOREIGN KEY (MaNhanVien) REFERENCES dbo.NHANVIEN(MaNV)
    );
    CREATE INDEX IX_LICHSUGIAOHANG_DonHang_ThoiGian ON dbo.LICHSUGIAOHANG(MaDonHang, ThoiGian DESC);
    CREATE INDEX IX_LICHSUGIAOHANG_NhanVien_TrangThai ON dbo.LICHSUGIAOHANG(MaNhanVien, TrangThai);
END;

COMMIT TRANSACTION;
